parameters:
    sonata.media.admin.media.class: Sonata\MediaBundle\Admin\ORM\MediaAdmin
    sonata.media.admin.media.controller: 'SonataMediaBundle:MediaAdmin'
    sonata.media.admin.media.translation_domain: SonataMediaBundle
    sonata.media.admin.gallery.class: Sonata\MediaBundle\Admin\GalleryAdmin
    sonata.media.admin.gallery.controller: 'SonataMediaBundle:GalleryAdmin'
    sonata.media.admin.gallery.translation_domain: '%sonata.media.admin.media.translation_domain%'
    sonata.media.admin.gallery_has_media.class: Sonata\MediaBundle\Admin\GalleryHasMediaAdmin
    sonata.media.admin.gallery_has_media.controller: 'SonataAdminBundle:CRUD'
    sonata.media.admin.gallery_has_media.translation_domain: '%sonata.media.admin.media.translation_domain%'

services:
    sonata.media.admin.media:
        class: %sonata.media.admin.media.class%
        tags:
            - { show_in_dashboard: false, name: sonata.admin, manager_type: orm, icon: '<i class="fa fa-archive"></i>', group: sonata_media, label_catalogue: '%sonata.media.admin.media.translation_domain%', label: media, label_translator_strategy: sonata.admin.label.strategy.underscore }
        arguments: ['', '%sonata.media.admin.media.entity%', '%sonata.media.admin.media.controller%', '@sonata.media.pool', '@sonata.classification.manager.category']
        calls:
            - [setModelManager, ['@sonata.media.admin.media.manager']]
            - [setTranslationDomain, ['%sonata.media.admin.media.translation_domain%']]
            - [setTemplates, [{ inner_list_row: 'SonataMediaBundle:MediaAdmin:inner_row_media.html.twig', outer_list_rows_mosaic: 'SonataMediaBundle:MediaAdmin:list_outer_rows_mosaic.html.twig', base_list_field: 'SonataAdminBundle:CRUD:base_list_flat_field.html.twig', list: 'SonataMediaBundle:MediaAdmin:list.html.twig', edit: 'SonataMediaBundle:MediaAdmin:edit.html.twig' }]]

    sonata.media.admin.media.manager:
        class: Sonata\MediaBundle\Admin\Manager\DoctrineORMManager
        arguments: ['@doctrine', '@sonata.media.manager.media']
    sonata.media.admin.gallery:
        class: %sonata.media.admin.gallery.class%
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: sonata_media, label: gallery, label_catalogue: '%sonata.media.admin.gallery.translation_domain%', label_translator_strategy: sonata.admin.label.strategy.underscore }
        arguments: ['', '%sonata.media.admin.gallery.entity%', '%sonata.media.admin.gallery.controller%', '@sonata.media.pool']
        calls:
            - [setTranslationDomain, ['%sonata.media.admin.gallery.translation_domain%']]
            - [setTemplates, [{ list: 'SonataMediaBundle:GalleryAdmin:list.html.twig' }]]

    sonata.media.admin.gallery_has_media:
        class: %sonata.media.admin.gallery_has_media.class%
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: sonata_media, label_catalogue: '%sonata.media.admin.gallery_has_media.translation_domain%', label: gallery_has_media, label_translator_strategy: sonata.admin.label.strategy.underscore }
        arguments: ['', '%sonata.media.admin.gallery_has_media.entity%', '%sonata.media.admin.gallery_has_media.controller%']
        calls:
            - [setTranslationDomain, ['%sonata.media.admin.gallery_has_media.translation_domain%']]

