package br.com.logics.flavis.model.repository.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import br.com.logics.flavis.model.entities.cliente.Cliente;
import br.com.logics.flavis.model.entities.equipamento.Equipamento;

import br.com.logics.flavis.model.entities.os.procedimento.ClienteEquipamento;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLIENTE_EQUIPAMENTO".
*/
public class ClienteEquipamentoDao extends AbstractDao<ClienteEquipamento, Long> {

    public static final String TABLENAME = "CLIENTE_EQUIPAMENTO";

    /**
     * Properties of entity ClienteEquipamento.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property EquipamentoId = new Property(1, Long.class, "equipamentoId", false, "EQUIPAMENTO_ID");
        public final static Property IsPmoc = new Property(2, boolean.class, "isPmoc", false, "IS_PMOC");
        public final static Property DataInicioPmoc = new Property(3, java.util.Date.class, "dataInicioPmoc", false, "DATA_INICIO_PMOC");
        public final static Property ClienteId = new Property(4, Long.class, "clienteId", false, "CLIENTE_ID");
        public final static Property Observacoes = new Property(5, String.class, "observacoes", false, "OBSERVACOES");
        public final static Property CreatedAt = new Property(6, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(7, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
    }

    private DaoSession daoSession;


    public ClienteEquipamentoDao(DaoConfig config) {
        super(config);
    }
    
    public ClienteEquipamentoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLIENTE_EQUIPAMENTO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"EQUIPAMENTO_ID\" INTEGER," + // 1: equipamentoId
                "\"IS_PMOC\" INTEGER NOT NULL ," + // 2: isPmoc
                "\"DATA_INICIO_PMOC\" INTEGER," + // 3: dataInicioPmoc
                "\"CLIENTE_ID\" INTEGER," + // 4: clienteId
                "\"OBSERVACOES\" TEXT," + // 5: observacoes
                "\"CREATED_AT\" INTEGER," + // 6: createdAt
                "\"UPDATED_AT\" INTEGER);"); // 7: updatedAt
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLIENTE_EQUIPAMENTO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ClienteEquipamento entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long equipamentoId = entity.getEquipamentoId();
        if (equipamentoId != null) {
            stmt.bindLong(2, equipamentoId);
        }
        stmt.bindLong(3, entity.getIsPmoc() ? 1L: 0L);
 
        java.util.Date dataInicioPmoc = entity.getDataInicioPmoc();
        if (dataInicioPmoc != null) {
            stmt.bindLong(4, dataInicioPmoc.getTime());
        }
 
        Long clienteId = entity.getClienteId();
        if (clienteId != null) {
            stmt.bindLong(5, clienteId);
        }
 
        String observacoes = entity.getObservacoes();
        if (observacoes != null) {
            stmt.bindString(6, observacoes);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(7, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(8, updatedAt.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ClienteEquipamento entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long equipamentoId = entity.getEquipamentoId();
        if (equipamentoId != null) {
            stmt.bindLong(2, equipamentoId);
        }
        stmt.bindLong(3, entity.getIsPmoc() ? 1L: 0L);
 
        java.util.Date dataInicioPmoc = entity.getDataInicioPmoc();
        if (dataInicioPmoc != null) {
            stmt.bindLong(4, dataInicioPmoc.getTime());
        }
 
        Long clienteId = entity.getClienteId();
        if (clienteId != null) {
            stmt.bindLong(5, clienteId);
        }
 
        String observacoes = entity.getObservacoes();
        if (observacoes != null) {
            stmt.bindString(6, observacoes);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(7, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(8, updatedAt.getTime());
        }
    }

    @Override
    protected final void attachEntity(ClienteEquipamento entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ClienteEquipamento readEntity(Cursor cursor, int offset) {
        ClienteEquipamento entity = new ClienteEquipamento( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // equipamentoId
            cursor.getShort(offset + 2) != 0, // isPmoc
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // dataInicioPmoc
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // clienteId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // observacoes
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)), // createdAt
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)) // updatedAt
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ClienteEquipamento entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEquipamentoId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIsPmoc(cursor.getShort(offset + 2) != 0);
        entity.setDataInicioPmoc(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setClienteId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setObservacoes(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCreatedAt(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
        entity.setUpdatedAt(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ClienteEquipamento entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ClienteEquipamento entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ClienteEquipamento entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEquipamentoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getClienteDao().getAllColumns());
            builder.append(" FROM CLIENTE_EQUIPAMENTO T");
            builder.append(" LEFT JOIN EQUIPAMENTO T0 ON T.\"EQUIPAMENTO_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN CLIENTE T1 ON T.\"CLIENTE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ClienteEquipamento loadCurrentDeep(Cursor cursor, boolean lock) {
        ClienteEquipamento entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Equipamento equipamento = loadCurrentOther(daoSession.getEquipamentoDao(), cursor, offset);
        entity.setEquipamento(equipamento);
        offset += daoSession.getEquipamentoDao().getAllColumns().length;

        Cliente cliente = loadCurrentOther(daoSession.getClienteDao(), cursor, offset);
        entity.setCliente(cliente);

        return entity;    
    }

    public ClienteEquipamento loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ClienteEquipamento> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ClienteEquipamento> list = new ArrayList<ClienteEquipamento>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ClienteEquipamento> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ClienteEquipamento> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
