package br.com.logics.flavis.model.repository.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import br.com.logics.flavis.model.entities.cliente.JoinClienteWithResponsavel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOIN_CLIENTE_WITH_RESPONSAVEL".
*/
public class JoinClienteWithResponsavelDao extends AbstractDao<JoinClienteWithResponsavel, Long> {

    public static final String TABLENAME = "JOIN_CLIENTE_WITH_RESPONSAVEL";

    /**
     * Properties of entity JoinClienteWithResponsavel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ClienteId = new Property(1, Long.class, "clienteId", false, "CLIENTE_ID");
        public final static Property ResponsavelId = new Property(2, Long.class, "responsavelId", false, "RESPONSAVEL_ID");
    }


    public JoinClienteWithResponsavelDao(DaoConfig config) {
        super(config);
    }
    
    public JoinClienteWithResponsavelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOIN_CLIENTE_WITH_RESPONSAVEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CLIENTE_ID\" INTEGER," + // 1: clienteId
                "\"RESPONSAVEL_ID\" INTEGER);"); // 2: responsavelId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOIN_CLIENTE_WITH_RESPONSAVEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JoinClienteWithResponsavel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long clienteId = entity.getClienteId();
        if (clienteId != null) {
            stmt.bindLong(2, clienteId);
        }
 
        Long responsavelId = entity.getResponsavelId();
        if (responsavelId != null) {
            stmt.bindLong(3, responsavelId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JoinClienteWithResponsavel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long clienteId = entity.getClienteId();
        if (clienteId != null) {
            stmt.bindLong(2, clienteId);
        }
 
        Long responsavelId = entity.getResponsavelId();
        if (responsavelId != null) {
            stmt.bindLong(3, responsavelId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JoinClienteWithResponsavel readEntity(Cursor cursor, int offset) {
        JoinClienteWithResponsavel entity = new JoinClienteWithResponsavel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // clienteId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // responsavelId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JoinClienteWithResponsavel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setClienteId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setResponsavelId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JoinClienteWithResponsavel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JoinClienteWithResponsavel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JoinClienteWithResponsavel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
