package br.com.logics.flavis.model.repository.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import br.com.logics.flavis.model.entities.cliente.TipoTelefone;

import br.com.logics.flavis.model.entities.cliente.Telefone;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TELEFONE".
*/
public class TelefoneDao extends AbstractDao<Telefone, Void> {

    public static final String TABLENAME = "TELEFONE";

    /**
     * Properties of entity Telefone.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", false, "ID");
        public final static Property Numero = new Property(1, String.class, "numero", false, "NUMERO");
        public final static Property ClienteId = new Property(2, Long.class, "clienteId", false, "CLIENTE_ID");
        public final static Property TipoTelefone = new Property(3, Long.class, "tipoTelefone", false, "TIPO_TELEFONE");
    }

    private DaoSession daoSession;

    private Query<Telefone> cliente_TelefonesQuery;

    public TelefoneDao(DaoConfig config) {
        super(config);
    }
    
    public TelefoneDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TELEFONE\" (" + //
                "\"ID\" INTEGER," + // 0: id
                "\"NUMERO\" TEXT," + // 1: numero
                "\"CLIENTE_ID\" INTEGER," + // 2: clienteId
                "\"TIPO_TELEFONE\" INTEGER);"); // 3: tipoTelefone
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TELEFONE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Telefone entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String numero = entity.getNumero();
        if (numero != null) {
            stmt.bindString(2, numero);
        }
 
        Long clienteId = entity.getClienteId();
        if (clienteId != null) {
            stmt.bindLong(3, clienteId);
        }
 
        Long tipoTelefone = entity.getTipoTelefone();
        if (tipoTelefone != null) {
            stmt.bindLong(4, tipoTelefone);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Telefone entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String numero = entity.getNumero();
        if (numero != null) {
            stmt.bindString(2, numero);
        }
 
        Long clienteId = entity.getClienteId();
        if (clienteId != null) {
            stmt.bindLong(3, clienteId);
        }
 
        Long tipoTelefone = entity.getTipoTelefone();
        if (tipoTelefone != null) {
            stmt.bindLong(4, tipoTelefone);
        }
    }

    @Override
    protected final void attachEntity(Telefone entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Telefone readEntity(Cursor cursor, int offset) {
        Telefone entity = new Telefone( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // numero
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // clienteId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // tipoTelefone
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Telefone entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNumero(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setClienteId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setTipoTelefone(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Telefone entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Telefone entity) {
        return null;
    }

    @Override
    public boolean hasKey(Telefone entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "telefones" to-many relationship of Cliente. */
    public List<Telefone> _queryCliente_Telefones(Long clienteId) {
        synchronized (this) {
            if (cliente_TelefonesQuery == null) {
                QueryBuilder<Telefone> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ClienteId.eq(null));
                cliente_TelefonesQuery = queryBuilder.build();
            }
        }
        Query<Telefone> query = cliente_TelefonesQuery.forCurrentThread();
        query.setParameter(0, clienteId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTipoTelefoneDao().getAllColumns());
            builder.append(" FROM TELEFONE T");
            builder.append(" LEFT JOIN TIPO_TELEFONE T0 ON T.\"TIPO_TELEFONE\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Telefone loadCurrentDeep(Cursor cursor, boolean lock) {
        Telefone entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TipoTelefone tipo = loadCurrentOther(daoSession.getTipoTelefoneDao(), cursor, offset);
        entity.setTipo(tipo);

        return entity;    
    }

    public Telefone loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Telefone> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Telefone> list = new ArrayList<Telefone>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Telefone> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Telefone> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
