package br.com.logics.flavis.model.repository.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import br.com.logics.flavis.model.entities.equipamento.TituloValor;

import br.com.logics.flavis.model.entities.equipamento.Valor;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VALOR".
*/
public class ValorDao extends AbstractDao<Valor, Long> {

    public static final String TABLENAME = "VALOR";

    /**
     * Properties of entity Valor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PropriedadeId = new Property(1, Long.class, "propriedadeId", false, "PROPRIEDADE_ID");
        public final static Property TituloId = new Property(2, Long.class, "tituloId", false, "TITULO_ID");
        public final static Property Valor = new Property(3, String.class, "valor", false, "VALOR");
        public final static Property Inserido = new Property(4, boolean.class, "inserido", false, "INSERIDO");
    }

    private DaoSession daoSession;

    private Query<Valor> propriedadeEquipamento_ValoresQuery;

    public ValorDao(DaoConfig config) {
        super(config);
    }
    
    public ValorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VALOR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PROPRIEDADE_ID\" INTEGER," + // 1: propriedadeId
                "\"TITULO_ID\" INTEGER," + // 2: tituloId
                "\"VALOR\" TEXT," + // 3: valor
                "\"INSERIDO\" INTEGER NOT NULL );"); // 4: inserido
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VALOR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Valor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long propriedadeId = entity.getPropriedadeId();
        if (propriedadeId != null) {
            stmt.bindLong(2, propriedadeId);
        }
 
        Long tituloId = entity.getTituloId();
        if (tituloId != null) {
            stmt.bindLong(3, tituloId);
        }
 
        String valor = entity.getValor();
        if (valor != null) {
            stmt.bindString(4, valor);
        }
        stmt.bindLong(5, entity.getInserido() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Valor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long propriedadeId = entity.getPropriedadeId();
        if (propriedadeId != null) {
            stmt.bindLong(2, propriedadeId);
        }
 
        Long tituloId = entity.getTituloId();
        if (tituloId != null) {
            stmt.bindLong(3, tituloId);
        }
 
        String valor = entity.getValor();
        if (valor != null) {
            stmt.bindString(4, valor);
        }
        stmt.bindLong(5, entity.getInserido() ? 1L: 0L);
    }

    @Override
    protected final void attachEntity(Valor entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Valor readEntity(Cursor cursor, int offset) {
        Valor entity = new Valor( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // propriedadeId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // tituloId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // valor
            cursor.getShort(offset + 4) != 0 // inserido
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Valor entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPropriedadeId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setTituloId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setValor(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setInserido(cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Valor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Valor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Valor entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "valores" to-many relationship of PropriedadeEquipamento. */
    public List<Valor> _queryPropriedadeEquipamento_Valores(Long propriedadeId) {
        synchronized (this) {
            if (propriedadeEquipamento_ValoresQuery == null) {
                QueryBuilder<Valor> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PropriedadeId.eq(null));
                propriedadeEquipamento_ValoresQuery = queryBuilder.build();
            }
        }
        Query<Valor> query = propriedadeEquipamento_ValoresQuery.forCurrentThread();
        query.setParameter(0, propriedadeId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTituloValorDao().getAllColumns());
            builder.append(" FROM VALOR T");
            builder.append(" LEFT JOIN TITULO_VALOR T0 ON T.\"TITULO_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Valor loadCurrentDeep(Cursor cursor, boolean lock) {
        Valor entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TituloValor titulo = loadCurrentOther(daoSession.getTituloValorDao(), cursor, offset);
        entity.setTitulo(titulo);

        return entity;    
    }

    public Valor loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Valor> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Valor> list = new ArrayList<Valor>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Valor> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Valor> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
