<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AgendamentoOrdemServico extends \AppBundle\Entity\AgendamentoOrdemServico implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'os', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'solicitante', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'colaborador', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'colaboradorExecutor', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'dataAgendada', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'horaAgendada', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'ocorrencia', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'temRelatorio', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'deletedAt');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'os', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'solicitante', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'colaborador', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'colaboradorExecutor', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'dataAgendada', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'horaAgendada', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'ocorrencia', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'temRelatorio', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\AgendamentoOrdemServico' . "\0" . 'deletedAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AgendamentoOrdemServico $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataAgendada($dataAgendada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataAgendada', array($dataAgendada));

        return parent::setDataAgendada($dataAgendada);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataAgendada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataAgendada', array());

        return parent::getDataAgendada();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraAgendada($horaAgendada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraAgendada', array($horaAgendada));

        return parent::setHoraAgendada($horaAgendada);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraAgendada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraAgendada', array());

        return parent::getHoraAgendada();
    }

    /**
     * {@inheritDoc}
     */
    public function setOcorrencia($ocorrencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOcorrencia', array($ocorrencia));

        return parent::setOcorrencia($ocorrencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getOcorrencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOcorrencia', array());

        return parent::getOcorrencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deletedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', array($deletedAt));

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', array());

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setOs(\AppBundle\Entity\OrdemServico $os)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOs', array($os));

        return parent::setOs($os);
    }

    /**
     * {@inheritDoc}
     */
    public function getOs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOs', array());

        return parent::getOs();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolicitante(\AppBundle\Entity\ResponsavelCliente $solicitante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolicitante', array($solicitante));

        return parent::setSolicitante($solicitante);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitante', array());

        return parent::getSolicitante();
    }

    /**
     * {@inheritDoc}
     */
    public function setColaborador(\AppBundle\Entity\Colaborador $colaborador = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColaborador', array($colaborador));

        return parent::setColaborador($colaborador);
    }

    /**
     * {@inheritDoc}
     */
    public function getColaborador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColaborador', array());

        return parent::getColaborador();
    }

    /**
     * {@inheritDoc}
     */
    public function setColaboradorExecutor(\AppBundle\Entity\Colaborador $colaboradorExecutor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColaboradorExecutor', array($colaboradorExecutor));

        return parent::setColaboradorExecutor($colaboradorExecutor);
    }

    /**
     * {@inheritDoc}
     */
    public function getColaboradorExecutor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColaboradorExecutor', array());

        return parent::getColaboradorExecutor();
    }

    /**
     * {@inheritDoc}
     */
    public function setTemRelatorio($temRelatorio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemRelatorio', array($temRelatorio));

        return parent::setTemRelatorio($temRelatorio);
    }

    /**
     * {@inheritDoc}
     */
    public function getTemRelatorio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemRelatorio', array());

        return parent::getTemRelatorio();
    }

}
