version: "3"

services:
    web:
        volumes:
            - files-sync:/var/www/html:nocopy
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    php6:
        volumes:
            - files-sync:/var/www/html:nocopy
    db:
        volumes:
            - files-sync:/var/www/html:nocopy

volumes:
    files-sync:
        external: true